resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource}
  - name: npm
    type: docker-image
    source:
      repository: docker.groupbyinc.com/concourse-npm-resource
      tag: 0.0.20
      email: {{docker-registry-email}}
      username: {{docker-registry-user}}
      password: {{docker-registry-passwd}}
      insecure_registries:
        - docker.groupbyinc.com:80

resources:
  - name: flux
    type: npm
    source:
      package: '@storefront/flux-capacitor'
  - name: core
    type: git
    source: &core-source
      uri: git@github.com:groupby/storefront-core.git
      branch: master
      private_key: {{git-repo-key}}
  - name: core-built
    type: git
    source:
      uri: git@github.com:groupby/storefront-core.git
      branch: concourse/update-flux
      private_key: {{git-repo-key}}
  - name: npm-cache
    type: npm-cache
    source:
      <<: *core-source
      yarn-support: true
      paths:
        - package.json
        - yarn.lock

jobs:
  - name: cache-npm-dependencies
    plan:
      - get: core
        trigger: true
      - get: npm-cache

  - name: update-flux
    serial: true
    plan:
      - get: flux
        trigger: true
      - aggregate:
        - get: core
          passed: [cache-npm-dependencies]
        - get: npm-cache
          passed: [cache-npm-dependencies]
      - task: release
        file: core/.concourse/tasks/release.yml
      - put: core-built
        params:
          repository: updated-core
          rebase: true

  - name: unit-test
    plan:
      - get: core-built
        trigger: true
        passed: [update-flux]
      - task: test
        file: core-built/.concourse/tasks/unit-test.yml
        input_mapping: {core: core-built}

  - name: release
    serial: true
    plan:
      - get: core-built
        passed: [unit-test]
        trigger: true
      - put: core
        params:
          repository: core-built
          rebase: true
