defaults:
  image: &image
    docker:
      - image: circleci/node
  yarn_cache: &yarn_cache
    key: yarn_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
  build_final_cache: &build_final_cache
    key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-all-{{ epoch }}
  build_paths: &build_paths
    - packages/@storefront/breadcrumbs/dist
    - packages/@storefront/breadcrumbs/esnext
    - packages/@storefront/collections/dist
    - packages/@storefront/collections/esnext
    - packages/@storefront/core/dist
    - packages/@storefront/core/esnext
    - packages/@storefront/details/dist
    - packages/@storefront/details/esnext
    - packages/@storefront/did-you-mean/dist
    - packages/@storefront/did-you-mean/esnext
    - packages/@storefront/flux-capacitor/dist
    - packages/@storefront/flux-capacitor/esnext
    - packages/@storefront/infinite-scroll/dist
    - packages/@storefront/infinite-scroll/esnext
    - packages/@storefront/navigation/dist
    - packages/@storefront/navigation/esnext
    - packages/@storefront/page-size/dist
    - packages/@storefront/page-size/esnext
    - packages/@storefront/paging/dist
    - packages/@storefront/paging/esnext
    - packages/@storefront/products/dist
    - packages/@storefront/products/esnext
    - packages/@storefront/query/dist
    - packages/@storefront/query/esnext
    - packages/@storefront/recommendations/dist
    - packages/@storefront/recommendations/esnext
    - packages/@storefront/record-count/dist
    - packages/@storefront/record-count/esnext
    - packages/@storefront/related-queries/dist
    - packages/@storefront/related-queries/esnext
    - packages/@storefront/sayt/dist
    - packages/@storefront/sayt/esnext
    - packages/@storefront/sort/dist
    - packages/@storefront/sort/esnext
    - packages/@storefront/structure/dist
    - packages/@storefront/structure/esnext
    - packages/@storefront/template/dist
    - packages/@storefront/template/esnext
  yarn_install: &yarn_install
    name: Install
    command: yarn
  requires_build_structure: &requires_build_structure
    requires:
      - build_structure
  requires_build: &requires_build
    requires:
      - build_final

version: 2.1

jobs:
  generate_cache_key_file:
    <<: *image
    working_directory: ~/
    steps:
      - run: date +%s > workflow-start
      - persist_to_workspace:
          root: ~/
          paths:
            - workflow-start

  build:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-
      - run:
          name: Dependencies
          command: sudo apt install -y rsync
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: |
            package="${CIRCLE_JOB#build_}"
            package="${package//_/-}"

            cd "packages/@storefront/${package}"
            yarn build
      - save_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths: *build_paths
  build_final:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_breadcrumbs-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_collections-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_core-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_details-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_did_you_mean-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_flux_capacitor-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_infinite_scroll-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_navigation-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_page_size-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_paging-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_products-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_query-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_recommendations-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_record_count-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_related_queries-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_sayt-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_sort-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_structure-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_template-
      - save_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-all-{{ epoch }}
          paths: *build_paths
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn

  unit_test:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-all-
      - run:
          <<: *yarn_install
      - run:
          name: Test
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/@storefront/${package}"
            yarn test
      - run:
          name: Upload coverage
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/@storefront/${package}"
            yarn uploadCoverage
  unit_test_final:
    <<: *image
    steps:
      - run: exit 0

  setup_release_branch:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Compute branch name
          command: echo "release/$(cat ../workflow-start)" > ../branch-name
      - run:
          name: Create branch
          command: git checkout -b "$(cat ../branch-name)/master"
      - run:
          name: Push branch
          command: git push -u origin HEAD

  docs:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          <<: *build_final_cache
      - run:
          <<: *yarn_install
      - run:
          name: Docs
          command: yarn docs
      - run:
          name: Commit
          command: git commit -m "Generate docs" -m "[ci skip]"
      - run:
          name: Push
          command: git push

workflows:
  version: 2

  build_test_release:
    jobs:
      - generate_cache_key_file
      - build:
          name: build_flux_capacitor
          requires:
            - generate_cache_key_file
      - build:
          name: build_core
          requires:
            - build_flux_capacitor
      - build:
          name: build_structure
          requires:
            - build_core
      - build:
          name: build_breadcrumbs
          <<: *requires_build_structure
      - build:
          name: build_collections
          <<: *requires_build_structure
      - build:
          name: build_details
          <<: *requires_build_structure
      - build:
          name: build_did_you_mean
          <<: *requires_build_structure
      - build:
          name: build_infinite_scroll
          <<: *requires_build_structure
      - build:
          name: build_navigation
          <<: *requires_build_structure
      - build:
          name: build_page_size
          <<: *requires_build_structure
      - build:
          name: build_paging
          <<: *requires_build_structure
      - build:
          name: build_products
          <<: *requires_build_structure
      - build:
          name: build_query
          <<: *requires_build_structure
      - build:
          name: build_recommendations
          <<: *requires_build_structure
      - build:
          name: build_record_count
          <<: *requires_build_structure
      - build:
          name: build_related_queries
          <<: *requires_build_structure
      - build:
          name: build_sayt
          <<: *requires_build_structure
      - build:
          name: build_sort
          <<: *requires_build_structure
      - build:
          name: build_template
          <<: *requires_build_structure
      - build_final:
          requires:
            - build_flux_capacitor
            - build_core
            - build_structure
            - build_breadcrumbs
            - build_collections
            - build_details
            - build_did_you_mean
            - build_infinite_scroll
            - build_navigation
            - build_page_size
            - build_paging
            - build_products
            - build_query
            - build_recommendations
            - build_record_count
            - build_related_queries
            - build_sayt
            - build_sort
            - build_template

      - unit_test:
          name: unit_test_flux_capacitor
          <<: *requires_build
      - unit_test:
          name: unit_test_core
          <<: *requires_build
      - unit_test:
          name: unit_test_structure
          <<: *requires_build
      - unit_test:
          name: unit_test_breadcrumbs
          <<: *requires_build
      - unit_test:
          name: unit_test_collections
          <<: *requires_build
      - unit_test:
          name: unit_test_details
          <<: *requires_build
      - unit_test:
          name: unit_test_did_you_mean
          <<: *requires_build
      - unit_test:
          name: unit_test_infinite_scroll
          <<: *requires_build
      - unit_test:
          name: unit_test_navigation
          <<: *requires_build
      - unit_test:
          name: unit_test_page_size
          <<: *requires_build
      - unit_test:
          name: unit_test_paging
          <<: *requires_build
      - unit_test:
          name: unit_test_products
          <<: *requires_build
      - unit_test:
          name: unit_test_query
          <<: *requires_build
      - unit_test:
          name: unit_test_recommendations
          <<: *requires_build
      - unit_test:
          name: unit_test_record_count
          <<: *requires_build
      - unit_test:
          name: unit_test_related_queries
          <<: *requires_build
      - unit_test:
          name: unit_test_sayt
          <<: *requires_build
      - unit_test:
          name: unit_test_sort
          <<: *requires_build
      - unit_test:
          name: unit_test_template
          <<: *requires_build
      - unit_test_final:
          requires:
            - unit_test_flux_capacitor
            - unit_test_core
            - unit_test_structure
            - unit_test_breadcrumbs
            - unit_test_collections
            - unit_test_details
            - unit_test_did_you_mean
            - unit_test_infinite_scroll
            - unit_test_navigation
            - unit_test_page_size
            - unit_test_paging
            - unit_test_products
            - unit_test_query
            - unit_test_recommendations
            - unit_test_record_count
            - unit_test_related_queries
            - unit_test_sayt
            - unit_test_sort
            - unit_test_template

      - setup_release_branch:
          requires:
            - unit_test_final
          filters:
            branches:
              only:
                - master
                - SF-1143
      - docs:
          requires:
            - setup_release_branch

