defaults:
  image: &image
    docker:
      - image: circleci/node
  yarn_cache: &yarn_cache
    key: yarn_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
  unit_test: &unit_test
    <<: *image
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - run:
          name: Test
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/${package}"
            yarn test
      - run:
          name: Upload coverage
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/${package}"
            yarn uploadCoverage
  requires_build: &requires_build
    requires:
      - build

version: 2

jobs:
  build:
    <<: *image
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          name: Dependencies
          command: apt install -y rsync
      - run:
          name: Install
          command: yarn
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn workspaces run build
      - persist_to_workspace:
         root: ~/
         paths:
           - project
  unit_test_flux_capacitor:
    <<: *unit_test
  unit_test_core:
    <<: *unit_test
  unit_test_structure:
    <<: *unit_test
  unit_test_breadcrumbs:
    <<: *unit_test
  unit_test_collections:
    <<: *unit_test
  unit_test_details:
    <<: *unit_test
  unit_test_did_you_mean:
    <<: *unit_test
  unit_test_infinite_scroll:
    <<: *unit_test
  unit_test_navigation:
    <<: *unit_test
  unit_test_page_size:
    <<: *unit_test
  unit_test_paging:
    <<: *unit_test
  unit_test_products:
    <<: *unit_test
  unit_test_query:
    <<: *unit_test
  unit_test_recommendations:
    <<: *unit_test
  unit_test_record_count:
    <<: *unit_test
  unit_test_related_queries:
    <<: *unit_test
  unit_test_sayt:
    <<: *unit_test
  unit_test_sort:
    <<: *unit_test
  unit_test_template:
    <<: *unit_test


workflows:
  version: 2

  build_test:
    jobs:
      - build
      - unit_test_flux_capacitor:
          <<: *requires_build
      - unit_test_core:
          <<: *requires_build
      - unit_test_structure:
          <<: *requires_build
      - unit_test_breadcrumbs:
          <<: *requires_build
      - unit_test_collections:
          <<: *requires_build
      - unit_test_details:
          <<: *requires_build
      - unit_test_did_you_mean:
          <<: *requires_build
      - unit_test_infinite_scroll:
          <<: *requires_build
      - unit_test_navigation:
          <<: *requires_build
      - unit_test_page_size:
          <<: *requires_build
      - unit_test_paging:
          <<: *requires_build
      - unit_test_products:
          <<: *requires_build
      - unit_test_query:
          <<: *requires_build
      - unit_test_recommendations:
          <<: *requires_build
      - unit_test_record_count:
          <<: *requires_build
      - unit_test_related_queries:
          <<: *requires_build
      - unit_test_sayt:
          <<: *requires_build
      - unit_test_sort:
          <<: *requires_build
      - unit_test_template:
          <<: *requires_build
