defaults:
  image: &image
    docker:
      - image: circleci/node
  yarn_cache: &yarn_cache
    key: yarn_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
  build_paths: &build_paths
    - packages/breadcrumbs/dist
    - packages/breadcrumbs/esnext
    - packages/collections/dist
    - packages/collections/esnext
    - packages/core/dist
    - packages/core/esnext
    - packages/details/dist
    - packages/details/esnext
    - packages/did-you-mean/dist
    - packages/did-you-mean/esnext
    - packages/flux-capacitor/dist
    - packages/flux-capacitor/esnext
    - packages/infinite-scroll/dist
    - packages/infinite-scroll/esnext
    - packages/navigation/dist
    - packages/navigation/esnext
    - packages/page-size/dist
    - packages/page-size/esnext
    - packages/paging/dist
    - packages/paging/esnext
    - packages/products/dist
    - packages/products/esnext
    - packages/query/dist
    - packages/query/esnext
    - packages/recommendations/dist
    - packages/recommendations/esnext
    - packages/record-count/dist
    - packages/record-count/esnext
    - packages/related-queries/dist
    - packages/related-queries/esnext
    - packages/sayt/dist
    - packages/sayt/esnext
    - packages/sort/dist
    - packages/sort/esnext
    - packages/structure/dist
    - packages/structure/esnext
    - packages/template/dist
    - packages/template/esnext
  build: &build
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-
      - run:
          name: Dependencies
          command: sudo apt install -y rsync
      - run:
          name: Install
          command: yarn
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: |
            package="${CIRCLE_JOB#build_}"
            package="${package//_/-}"

            cd "packages/${package}"
            yarn build
      - save_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths: *build_paths

  unit_test: &unit_test
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-all-
      - run:
          name: Install
          command: yarn
      - run:
          name: Test
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/${package}"
            yarn test
      - run:
          name: Upload coverage
          command: |
            package="${CIRCLE_JOB#unit_test_}"
            package="${package//_/-}"

            cd "packages/${package}"
            yarn uploadCoverage
  requires_build_structure: &requires_build_structure
    requires:
      - build_structure
  requires_build: &requires_build
    requires:
      - build_final

version: 2.1

jobs:
  generate_cache_key_file:
    <<: *image
    working_directory: ~/
    steps:
      - run: date +%s > workflow-start
      - persist_to_workspace:
          root: ~/
          paths:
            - workflow-start
  build:
    <<: *build
  build_breadcrumbs:
    <<: *build
  build_collections:
    <<: *build
  build_core:
    <<: *build
  build_details:
    <<: *build
  build_did_you_mean:
    <<: *build
  build_infinite_scroll:
    <<: *build
  build_navigation:
    <<: *build
  build_page_size:
    <<: *build
  build_paging:
    <<: *build
  build_products:
    <<: *build
  build_query:
    <<: *build
  build_recommendations:
    <<: *build
  build_record_count:
    <<: *build
  build_related_queries:
    <<: *build
  build_sayt:
    <<: *build
  build_sort:
    <<: *build
  build_structure:
    <<: *build
  build_template:
    <<: *build
  build_final:
    <<: *image
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_breadcrumbs-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_collections-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_core-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_details-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_did_you_mean-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_flux_capacitor-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_infinite_scroll-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_navigation-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_page_size-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_paging-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_products-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_query-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_recommendations-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_record_count-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_related_queries-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_sayt-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_sort-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_structure-
      - restore_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-build_template-
      - save_cache:
          key: build_cache-v{{ .Environment.CI_CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}-{{ checksum "../workflow-start" }}-all-{{ epoch }}
          paths: *build_paths
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn

  unit_test_flux_capacitor:
    <<: *unit_test
  unit_test_core:
    <<: *unit_test
  unit_test_structure:
    <<: *unit_test
  unit_test_breadcrumbs:
    <<: *unit_test
  unit_test_collections:
    <<: *unit_test
  unit_test_details:
    <<: *unit_test
  unit_test_did_you_mean:
    <<: *unit_test
  unit_test_infinite_scroll:
    <<: *unit_test
  unit_test_navigation:
    <<: *unit_test
  unit_test_page_size:
    <<: *unit_test
  unit_test_paging:
    <<: *unit_test
  unit_test_products:
    <<: *unit_test
  unit_test_query:
    <<: *unit_test
  unit_test_recommendations:
    <<: *unit_test
  unit_test_record_count:
    <<: *unit_test
  unit_test_related_queries:
    <<: *unit_test
  unit_test_sayt:
    <<: *unit_test
  unit_test_sort:
    <<: *unit_test
  unit_test_template:
    <<: *unit_test


workflows:
  version: 2

  build_test:
    jobs:
      - generate_cache_key_file
      - build:
          name: build_flux_capacitor
          requires:
            - generate_cache_key_file
      - build_core:
          requires:
            - build_flux_capacitor
      - build_structure:
          requires:
            - build_core
      - build_breadcrumbs:
          <<: *requires_build_structure
      - build_collections:
          <<: *requires_build_structure
      - build_details:
          <<: *requires_build_structure
      - build_did_you_mean:
          <<: *requires_build_structure
      - build_infinite_scroll:
          <<: *requires_build_structure
      - build_navigation:
          <<: *requires_build_structure
      - build_page_size:
          <<: *requires_build_structure
      - build_paging:
          <<: *requires_build_structure
      - build_products:
          <<: *requires_build_structure
      - build_query:
          <<: *requires_build_structure
      - build_recommendations:
          <<: *requires_build_structure
      - build_record_count:
          <<: *requires_build_structure
      - build_related_queries:
          <<: *requires_build_structure
      - build_sayt:
          <<: *requires_build_structure
      - build_sort:
          <<: *requires_build_structure
      - build_template:
          <<: *requires_build_structure
      - build_final:
          requires:
            - build_flux_capacitor
            - build_core
            - build_structure
            - build_breadcrumbs
            - build_collections
            - build_details
            - build_did_you_mean
            - build_infinite_scroll
            - build_navigation
            - build_page_size
            - build_paging
            - build_products
            - build_query
            - build_recommendations
            - build_record_count
            - build_related_queries
            - build_sayt
            - build_sort
            - build_template

      - unit_test_flux_capacitor:
          <<: *requires_build
      - unit_test_core:
          <<: *requires_build
      - unit_test_structure:
          <<: *requires_build
      - unit_test_breadcrumbs:
          <<: *requires_build
      - unit_test_collections:
          <<: *requires_build
      - unit_test_details:
          <<: *requires_build
      - unit_test_did_you_mean:
          <<: *requires_build
      - unit_test_infinite_scroll:
          <<: *requires_build
      - unit_test_navigation:
          <<: *requires_build
      - unit_test_page_size:
          <<: *requires_build
      - unit_test_paging:
          <<: *requires_build
      - unit_test_products:
          <<: *requires_build
      - unit_test_query:
          <<: *requires_build
      - unit_test_recommendations:
          <<: *requires_build
      - unit_test_record_count:
          <<: *requires_build
      - unit_test_related_queries:
          <<: *requires_build
      - unit_test_sayt:
          <<: *requires_build
      - unit_test_sort:
          <<: *requires_build
      - unit_test_template:
          <<: *requires_build
