platform: linux

image_resource:
  type: docker-image
  source: {repository: i6group/docker-node-git-yarn}

inputs:
  - name: core

run:
  path: sh
  dir: core
  args:
    - -exc
    - |
      yarn --no-progress
      yarn test
