import { bootstrap } from '@storefront/testing';
import * as chai from 'chai';

bootstrap(chai, __dirname, [
  '../src/paging/index.html',
  '../../structure/dist/button/index.html',
  '../../structure/dist/carousel/index.html',
  '../../structure/dist/carousel/index.css',
  '../../structure/dist/carousel-slide/index.html',
  '../../structure/dist/custom-select/index.html',
  '../../structure/dist/custom-select/index.css',
  '../../structure/dist/filtered-list/index.html',
  '../../structure/dist/generic-paging/index.html',
  '../../structure/dist/icon/index.html',
  '../../structure/dist/infinite-list/index.html',
  '../../structure/dist/infinite-list/index.css',
  '../../structure/dist/link/index.html',
  '../../structure/dist/list/index.html',
  '../../structure/dist/list/index.css',
  '../../structure/dist/modal/index.html',
  '../../structure/dist/modal/index.css',
  '../../structure/dist/native-select/index.html',
  '../../structure/dist/paged-list/index.html',
  '../../structure/dist/pager/index.html',
  '../../structure/dist/pages/index.html',
  '../../structure/dist/pill/index.html',
  '../../structure/dist/pill/index.css',
  '../../structure/dist/select/index.html',
  '../../structure/dist/slider/index.html',
  '../../structure/dist/slider/index.css',
  '../../structure/dist/swatch/index.html',
  '../../structure/dist/swatches/index.html',
  '../../structure/dist/terminal-pager/index.html',
  '../../structure/dist/toggle/index.html',
  '../../structure/dist/toggle/index.css',
  '../../structure/dist/tooltip/index.html',
  '../../structure/dist/tooltip/index.css',
]);
